services:
  db:
    image: postgres:15-alpine
    container_name: iot_analytics-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: iot_analytics-redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: iot_analytics-web
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - static_data:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:stable-alpine
    container_name: iot_analytics-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
