services:
  db:
    image: postgres:15-alpine
    container_name: iot_analytics-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: iot_analytics-redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: iot_analytics-web
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - static_data:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - mosquitto

  nginx:
    image: nginx:stable-alpine
    container_name: iot_analytics-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: iot_analytics-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/config
    env_file:
      - .env
    entrypoint: >
      sh -c "
      echo '${MQTT_USERNAME}:${MQTT_PASSWORD}' > /mosquitto/config/credentials && 
      mosquitto_passwd -U /mosquitto/config/credentials && 
      mv /mosquitto/config/credentials /mosquitto/config/passwordfile &&
      exec mosquitto -c /mosquitto/config/mosquitto.conf"

  mqtt-subscriber:
    build: .
    container_name: iot_analytics-subscriber
    env_file:
      - .env
    command: poetry run python iot/mqtt_client.py
    depends_on:
      - db
      - redis
      - mosquitto

volumes:
  postgres_data:
  static_data:
  mosquitto_data:
